name: Manual workflow

on:
  push:
  schedule:
    - cron: "0 5,17 * * *"
  workflow_dispatch:

jobs:
  automation:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Keep Alive
      uses: gautamkrishnar/keepalive-workflow@master
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.4.1
      
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
        
    # - name: Install dependencies
    #   run: npm install

    - uses: actions/setup-python@v2

    - name: Setup Config.yml 
      uses: jannekem/run-python-script-action@v1
      env:
        USERNAME: ${{secrets.USERNAME}}
        PASSWORD: ${{secrets.PASSWORD}}
        LINE_TOKEN: ${{secrets.LINE_TOKEN}}
      with:
        script: |
          import os
          with open('config.yml', 'r'):
            data = file.read()
          data = data.replace("$username", os.environ['USERNAME'])
          data = data.replace("$password", os.environ['PASSWORD'])
          data = data.replace("$line_token", os.environ['LINE_TOKEN'])
          with open('config.yml', 'w') as file:
            file.write(data)

    - name: Bahamut Automation
      run: npx bahamut-automation -c config.yml
      
